services:
  - type: web
    name: email-validator
    env: python
    buildCommand: "pip install -r requirements.txt && cd frontend && npm install && npm run build"
    startCommand: "gunicorn app_anon_history:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
